RES = 'results'
KAL_IDX = RES + '/select_transcripts.kidx'
FASTA = '../data/select_transcripts.fa'
LEFT = '../data/sample_01_1.fasta'
RIGHT = '../data/sample_01_2.fasta'
KAL_OUT = RES + '/kal_out/abundance.h5'

rule all:
    input:
        KAL_IDX,
        RES + '/kal_out/abundance.h5'

rule kallisto_index:
    input:
        FASTA
    output:
        KAL_IDX
    shell:
        'kallisto index -i {KAL_IDX} {FASTA}'

rule kallisto:
    input:
        LEFT,
        RIGHT
    output:
        RES + '/{id}',
        RES + '/{id}/abundance.h5'
    benchmark:
        'benchmarks/kallisto/{id}.json'
    shell:
        'kallisto quant -i ' + KAL_IDX + ' '
        '-o {output[0]} '
        '{LEFT} {RIGHT}'

